=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema1/Tema2/Hoja2/ejemplo.dtd
<!ELEMENT diario (nombre,entrada+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT entrada (fecha,festivo?,contenido,lectura*)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT festivo EMPTY>
<!ELEMENT contenido (#PCDATA)>
<!ELEMENT lectura (#PCDATA)>

=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema1/Tema2/Hoja2/ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE diario SYSTEM "ejemplo.dtd">

<diario>
    <nombre>Luis PÃ©rez</nombre>
    <entrada>
        <fecha>2023-10-17</fecha>
        <contenido>Querido diario...</contenido>
    </entrada>
    <entrada>
        <fecha>2023-10-16</fecha>
        <festivo />
        <contenido>Querido diario...</contenido>
        <lectura>El camino (Miguel Delibes)</lectura>
        <lectura>El nombre del viento (Patrick Rothfuss)</lectura>
    </entrada>
    <entrada>
        <fecha>2023-10-15</fecha>
        <festivo />
        <contenido>Querido diario...</contenido>
        <lectura>El nombre del viento (Patrick Rothfuss)</lectura>
    </entrada>
</diario>
