=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema1/Tema2/Hoja1/pacientes.dtd
<!-- 
Añade al archivo un DTD interno que permita validarlo, siguiendo las siguientes premisas:
• El elemento pacientes puede tener varios elementos paciente, o ninguno.
• Un elemento paciente debe tener obligatoriamente un hijo nombre y un hijo que podrá ser
dni o num_seg_social, pero no ambos. El motivo es que si un paciente no tiene número de la
seguridad social, se le dará de alta con su DNI.
-->
<!ELEMENT pacientes (paciente*)>
<!ELEMENT paciente (nombre, (dni*|num_seg_social*), alergias?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT num_seg_social (#PCDATA)>
<!ELEMENT alergias EMPTY>

=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema1/Tema2/Hoja1/pacientes.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
En una clínica utilizan un archivo XML para guardar los datos de sus clientes. Aquí podemos ver
un ejemplo:    
-->

<!DOCTYPE pacientes SYSTEM "pacientes.dtd">
<pacientes>
    <paciente>
        <nombre>Sofía Ruiz</nombre>
        <dni>29921001H</dni>
    </paciente>
    <paciente>
        <nombre>Manuel Campos</nombre>
        <num_seg_social>88399110J</num_seg_social>
        <alergias/>
    </paciente>
</pacientes>
