=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema1/Tema2/Hoja1/persona.dtd
<!-- 
Usamos + si queremos que aparezca una o mas veces.
Usamos * si es opcional que aparezca o no.
Usamos ? si queremos que aparezca (Una vez) o no.
-->
<!ELEMENT persona (nombre,apellido+, extra*, ocasion?, combustible?, gasolina*)>
<!-- Usamos (#PCDATA) cuando metamos info dentro -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT extra (#PCDATA)>
<!-- Usamos EMPTY porque no va a tener nada dentro -->
<!ELEMENT ocasion EMPTY>
<!-- Usamos (gasolina|diesel) porque dentro de combustible puede tener esas dos opciones -->
<!ELEMENT combustible (gasolina|diesel|electrico|hibrido)>
<!ELEMENT gasolina EMPTY>
<!ELEMENT diesel EMPTY>
<!ELEMENT electrico EMPTY>
<!ELEMENT hibrido EMPTY>

=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema1/Tema2/Hoja1/persona.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE persona SYSTEM "persona.dtd">
<persona>
	<nombre>Amadeo</nombre>
	<apellido>Martínez</apellido>
	<apellido>López</apellido>
	<extra>Elevalunas electrico</extra>
	<extra>Techo solar</extra>
	<ocasion/>
	<combustible>
		<gasolina/>
	</combustible>

</persona>
