=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema3/Ejemplos/Ejemplo01/Ejemplo1.xsd
<?xml version="1.0" encoding="UTF-8"?>  

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libros">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="libro" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="libro" >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titulo" />
                <xs:element ref="autor" />
                <xs:element ref="nacionalidad" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="titulo" >
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string" >
                    <xs:attribute ref="isbn" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="isbn" />
    <xs:element name="autor" />
    <xs:element name="nacionalidad" />
    <xs:element name="nacional" />
    <xs:element name="extranjera" />
</xs:schema>

=== manu989898/JavaClase/Eclipse-Workspace-LM/Tema3/Ejemplos/Ejemplo01/Ejemplo01.xml
<?xml version="1.0" encoding="UTF-8"?>  

<libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejemplo1.xsd" >
    <libro>
        <titulo>El quijote</titulo>
        <autor>Miguel de cervantes</autor>
        <nacionalidad>
            <nacional/>
        </nacionalidad>
    </libro>
    <libro>
        <titulo isbn="123-214-548">Estudio en escarlata</titulo>
        <autor>Arthur Conan Doyle</autor>
        <nacionalidad>
            <extranjero/>
        </nacionalidad>
    </libro>
</libros>
